# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: none # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes
DISABLE_LINTERS:
  - JAVASCRIPT_STANDARD
  - TYPESCRIPT_ES
  - TYPESCRIPT_STANDARD
  - TYPESCRIPT_PRETTIER
  - REPOSITORY_DEVSKIM
  - SPELL_LYCHEE
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
DISABLE_ERRORS: true
REPOSITORY_CHECKOV_ARGUMENTS:
  - 'checkov --skip-check CKV2_GHA_1'
MARKDOWN_MARKDOWNLINT_FILE_EXTENSIONS: ['.md', '.mdx']
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: (node_modules|\.changeset)\/.*$
