export interface NoRestrictedSyntaxSlice {
  selector: string;
  message: string;
}

export interface Entry {
  ruleName: string;
  parentPluginName: string;
  severity: NumericSeverity;
  ruleOptions: RuleOptionsConfig;
  affectedFiles: string;
  docs: {
    description: string;
    url: string;
  };
}

export type NumericSeverity = 0 | 1 | 2;
export type StringSeverity = 'error' | 'warn' | 'off';
export type Severity = NumericSeverity | StringSeverity;

export type RuleOptions =
  | [Severity, ...(Record<string, unknown> | string)[]]
  | Severity
  | undefined;

export type RuleOptionsConfig = (Record<string, any> | string)[];

export interface SheriffConfigurablePlugins {
  /**
   * React support.
   */
  react: boolean;
  /**
   * Lodash support.
   */
  lodash: boolean;
  /**
   * Remeda support.
   */
  remeda: boolean;
  /**
   * Nextjs support.
   */
  next: boolean;
  /**
   * Astro support.
   */
  astro: boolean;
  /**
   * Playwright support.
   */
  playwright: boolean;
  /**
   * Storybook support.
   */
  storybook: boolean;
  /**
   * Jest support. Select this or vitest, not both.
   */
  jest: boolean;
  /**
   * Vitest support. Select this or jest, not both.
   */
  vitest: boolean;
}

export type TsProjectType = 'projectService' | 'project' | false | null;

export interface SheriffSettings extends Partial<SheriffConfigurablePlugins> {
  /**
   * This parameter allows you to override the paths for some Sheriff settings.
   */
  pathsOverrides?: {
    /**
     * With this setting, if you have multiple tsconfig.json files in your project (like tsconfig.json, tsconfig.eslint.json, tsconfig.node.json, etc...) you can specify which config Sheriff will pickup. You can also specify a list of paths, see: https://typescript-eslint.io/linting/typed-linting/monorepos/#one-tsconfigjson-per-package-and-an-optional-one-in-the-root.
     *
     * @deprecated This setting is now unsupported. `projectService` is now enabled by default. If you need to specify a custom `tsconfig.json` file, set `tsProjectType` to false or null and define a new configuration object with the `project`: /path/to/tsconfig.json property.
     */
    tsconfigLocation?: string | string[];
    /**
     * This setting overrides the default Sheriff filepaths for Vitest and Jest linting. It accepts an array of filepaths, dictaced by minimatch syntax. Sheriff will apply Jest or Vitest rules only on these files.
     */
    tests?: string[];
    /**
     * This setting overrides the default Sheriff filepaths for Playwright linting. It accepts an array of filepaths, dictaced by minimatch syntax. Sheriff will apply Playwright rules only on these files.
     */
    playwrightTests?: string[];
  };
  /**
   * This setting apply some ignore patterns to the whole config.
   */
  ignores?: {
    /**
     * Some commonly ignored folders.
     */
    recommended?: boolean;
    /**
     * With this setting, Sheriff will ignore all the files that are currently ignored by git. Chances are that if you are ignoring a file in git, you don't want to lint it, which usually is the case with temporary and autogenerated files.
     */
    inheritedFromGitignore?: boolean;
  };
  /**
   * This setting accepts an array of filepaths, described by minimatch syntax. Only the matching files found in this array will be linted. All other files will be ignored. This is useful if you want to lint only a subset of your project.
   */
  files?: string[];
  /**
   * This setting allows you to specify the typescript-eslint parserOption "project type" that Sheriff will use.
   * In line with typescript-eslint specifications, `projectService` is enabled by default, but you can fallback to `project` or disable the setting entirely, if you want. This can be especially useful if you want to use a custom `tsconfig.json` file for any reason.
   *
   * See: https://typescript-eslint.io/packages/parser/#projectservice
   *
   * **WARNING**: setting this option to false or null will disable every type-aware linting rule and will possibly break Sheriff in multiple ways. Only disable this if you want to manually re-configure the typescript-eslint parserOptions.
   *
   * @default 'projectService'
   */
  tsProjectType?: TsProjectType;
}

export interface ServerResponse {
  compiledConfig: Entry[];
  pluginsNames: string[];
  totalAvailableRulesAmount?: number;
}
