name: '🐛 Bug Report'
description: Report an issue or a bug
labels: ['bug', 'triaging']
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Your environment
      description: Include as many relevant details about the environment you experienced the bug in.
      placeholder: |
        - Environment name and version (e.g. Chrome 89, Node.js 16.4):
        - Operating System and version (e.g. Ubuntu 20.04.2 LTS):
        - Package manager and version (e.g. pnpm 7.19.1):
    validations:
      required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Bug description
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Project
      description: Please choose the project related to the bug you found.
      multiple: false
      options:
        - 'eslint-config-sheriff'
        - '@sherifforg/cli'
        - '@sherifforg/create-config'
        - the documentation website
        - the root of the monorepository
  - type: input
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: Please provide a link to a repo that can reproduce the problem you ran into.
      placeholder: Reproduction link
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Write down the steps to reproduce the bug. You should start with a fresh installation, or your git repository linked above.
      placeholder: |
        1. Step 1...
        2. Step 2...
        3. Step 3...
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/AndreaPontrandolfo/sheriff/blob/master/CODE_OF_CONDUCT.md)
          required: true
        - label: I have read the [Contributing Guidelines on Issues](https://github.com/AndreaPontrandolfo/sheriff/blob/master/CONTRIBUTING.md#opening-a-new-issue).
          required: true
  - type: checkboxes
    attributes:
      label: I will submit a PR
      description: If you are willing to submit a PR to fix this issue, please check the box below.
      options:
        - label: I'd be willing to submit a PR for this issue.
