blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/AndreaPontrandolfo/sheriff/discussions
    about: Use the Discussions tab to propose ideas for improvement or to ask for help.
