import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'link',
      label: '🌤 Changelog',
      href: 'https://github.com/AndreaPontrandolfo/sheriff/releases',
    },
  ],
};

// eslint-disable-next-line import/no-default-export
export default sidebars;
