/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as DocsOgSplatRouteImport } from './routes/docs-og/$'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as BlogOgSlugRouteImport } from './routes/blog-og/$slug'
import { Route as ApiStargazersRouteImport } from './routes/api/stargazers'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as LlmsMdxSplatRouteImport } from './routes/llms.mdx/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsOgSplatRoute = DocsOgSplatRouteImport.update({
  id: '/docs-og/$',
  path: '/docs-og/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogOgSlugRoute = BlogOgSlugRouteImport.update({
  id: '/blog-og/$slug',
  path: '/blog-og/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStargazersRoute = ApiStargazersRouteImport.update({
  id: '/api/stargazers',
  path: '/api/stargazers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsMdxSplatRoute = LlmsMdxSplatRouteImport.update({
  id: '/llms/mdx/$',
  path: '/llms/mdx/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stargazers': typeof ApiStargazersRoute
  '/blog-og/$slug': typeof BlogOgSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs-og/$': typeof DocsOgSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/llms/mdx/$': typeof LlmsMdxSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stargazers': typeof ApiStargazersRoute
  '/blog-og/$slug': typeof BlogOgSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs-og/$': typeof DocsOgSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog': typeof BlogIndexRoute
  '/llms/mdx/$': typeof LlmsMdxSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stargazers': typeof ApiStargazersRoute
  '/blog-og/$slug': typeof BlogOgSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/docs-og/$': typeof DocsOgSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/llms/mdx/$': typeof LlmsMdxSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/search'
    | '/api/stargazers'
    | '/blog-og/$slug'
    | '/blog/$slug'
    | '/docs-og/$'
    | '/docs/$'
    | '/blog/'
    | '/llms/mdx/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/search'
    | '/api/stargazers'
    | '/blog-og/$slug'
    | '/blog/$slug'
    | '/docs-og/$'
    | '/docs/$'
    | '/blog'
    | '/llms/mdx/$'
  id:
    | '__root__'
    | '/'
    | '/api/search'
    | '/api/stargazers'
    | '/blog-og/$slug'
    | '/blog/$slug'
    | '/docs-og/$'
    | '/docs/$'
    | '/blog/'
    | '/llms/mdx/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiStargazersRoute: typeof ApiStargazersRoute
  BlogOgSlugRoute: typeof BlogOgSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DocsOgSplatRoute: typeof DocsOgSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LlmsMdxSplatRoute: typeof LlmsMdxSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs-og/$': {
      id: '/docs-og/$'
      path: '/docs-og/$'
      fullPath: '/docs-og/$'
      preLoaderRoute: typeof DocsOgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-og/$slug': {
      id: '/blog-og/$slug'
      path: '/blog-og/$slug'
      fullPath: '/blog-og/$slug'
      preLoaderRoute: typeof BlogOgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stargazers': {
      id: '/api/stargazers'
      path: '/api/stargazers'
      fullPath: '/api/stargazers'
      preLoaderRoute: typeof ApiStargazersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms/mdx/$': {
      id: '/llms/mdx/$'
      path: '/llms/mdx/$'
      fullPath: '/llms/mdx/$'
      preLoaderRoute: typeof LlmsMdxSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiStargazersRoute: ApiStargazersRoute,
  BlogOgSlugRoute: BlogOgSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  DocsOgSplatRoute: DocsOgSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  LlmsMdxSplatRoute: LlmsMdxSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
