name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          any-of-labels: 'feedback-requested'
          close-issue-message: 'closed due to inactivity'
          stale-issue-message: 'marking as stale due to inactivity'
